<?php

?>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "blog": {
                            "component": "Inchoo_Blog/js/blog",
                            "title": "Hello world"
                        }
                    }
                }
            }
        }
</script>
